language: python
python:
    - "2.6"
    - "2.7"

branches:
  only:
    - master

notifications:
  email:
    - ben@groovie.org
    - hschlichting@mozilla.com
  irc: "irc.mozilla.org#services-dev"

before_install:
    - sudo apt-get update >/dev/null 2>&1
    - sudo apt-get install libevent-dev libpcre3-dev >/dev/null 2>&1
    - sudo aptitude -y remove dsc cassandra

install:
    - make build
    - bin/pip install gevent >/dev/null 2>&1
    - make cassandra

script: make test
